Update error message

diff --git a/branchupdate b/branchupdate
--- a/branchupdate
+++ b/branchupdate
@@ -4,7 +4,7 @@
 #Assumes remote branch is named upstream
 
 if [[ ! -d ./.git ]]; then
-  echo "error: This is not a git repository" >&2; exit 1
+  echo "error: Current directory is not a git repository" >&2; exit 1
 fi
 
 REMOTE="upstream"
